"""add song difficulty and tag sort_order

Revision ID: 3abe5a9262f8
Revises: 81c6c259e2d5
Create Date: 2026-06-08 19:01:58.507248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3abe5a9262f8'
down_revision: Union[str, Sequence[str], None] = '81c6c259e2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('Song', sa.Column('difficulty', sa.Integer(), nullable=False))
    #op.add_column('Tag', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.add_column('Song', sa.Column('difficulty', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('Tag', sa.Column('sort_order', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tag', 'sort_order')
    op.drop_column('Song', 'difficulty')
    # ### end Alembic commands ###
