"""add auth to User

Revision ID: 81c6c259e2d5
Revises: a04e3853ca4a
Create Date: 2026-06-01 20:36:56.089185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c6c259e2d5'
down_revision: Union[str, Sequence[str], None] = 'a04e3853ca4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('auths', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'auths')
    # ### end Alembic commands ###
