"""initial checkin

Revision ID: 9b32508a3c00
Revises: 
Create Date: 2026-04-21 00:14:24.646236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b32508a3c00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('org', sa.String(length=40), nullable=False),
    sa.Column('override', sa.String(length=40), nullable=False),
    sa.Column('utility', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('VoicePart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('range_low', sa.Integer(), nullable=True),
    sa.Column('range_high', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SongTag',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['Song.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['Tag.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'tag_id')
    )
    op.create_table('SongVoicePart',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('range_low', sa.Integer(), nullable=True),
    sa.Column('range_high', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['VoicePart.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['Song.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'part_id')
    )
    op.create_table('SongVoicePartQual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('performance_ready', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['VoicePart.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['Song.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SongVoicePartQual')
    op.drop_table('SongVoicePart')
    op.drop_table('SongTag')
    op.drop_table('VoicePart')
    op.drop_table('User')
    op.drop_table('Tag')
    op.drop_table('Song')
    # ### end Alembic commands ###
