"""add slack_id

Revision ID: a04e3853ca4a
Revises: 9b32508a3c00
Create Date: 2026-06-01 17:19:56.245955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04e3853ca4a'
down_revision: Union[str, Sequence[str], None] = '9b32508a3c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('slack_id', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'slack_id')
    # ### end Alembic commands ###
