"""add song duration and keys

Revision ID: ad07ccef8a2d
Revises: b46fee7518d9
Create Date: 2026-09-07 10:23:10.146844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad07ccef8a2d'
down_revision: Union[str, Sequence[str], None] = 'b46fee7518d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Song', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('Song', sa.Column('written_key', sa.String(length=8), nullable=True))
    op.add_column('Song', sa.Column('performance_key', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Song', 'performance_key')
    op.drop_column('Song', 'written_key')
    op.drop_column('Song', 'duration')
    # ### end Alembic commands ###
