"""add gig object and supporting tables

Revision ID: b46fee7518d9
Revises: 792f43677894
Create Date: 2026-09-01 00:57:32.472351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46fee7518d9'
down_revision: Union[str, Sequence[str], None] = '792f43677894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Gig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('comments', sa.String(length=255), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('thread_ts', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GigSetListItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gig_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('song_key', sa.String(length=8), nullable=True),
    sa.Column('in_setlist', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['gig_id'], ['Gig.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['Song.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GigSinger',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gig_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gig_id'], ['Gig.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'gig_id')
    )
    op.create_table('GigSongVoicePartAssignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gig_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performance_ready', sa.Boolean(), nullable=False),
    sa.Column('waiver', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['gig_id'], ['Gig.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['VoicePart.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['Song.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GigSongVoicePartAssignment')
    op.drop_table('GigSinger')
    op.drop_table('GigSetListItem')
    op.drop_table('Gig')
    # ### end Alembic commands ###
