"""add set item duration

Revision ID: dce87e06c704
Revises: ad07ccef8a2d
Create Date: 2026-09-09 15:06:57.066502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce87e06c704'
down_revision: Union[str, Sequence[str], None] = 'ad07ccef8a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GigSetListItem', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GigSetListItem', 'duration')
    # ### end Alembic commands ###
